name: CI
on:
  push:
    branches:    
      - sh
      - py
      - go
  watch:
    types: started
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: ci for sh ver
      env:
        GW_GTW: ${{ secrets.GW_GTW }}
        GW_USERNAME: ${{ secrets.GW_USERNAME }}
        GW_PASSWORD: ${{ secrets.GW_PASSWORD }}
      run: |
        git checkout sh
        bash giwifi-gear-sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -q -l
        sleep 2
        bash giwifi-gear-sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -t pc -l
        sleep 2
        bash giwifi-gear-sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -q -l
        sleep 2
        bash giwifi-gear-sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -q mac
        sleep 2
        bash giwifi-gear-sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -q -l
        sleep 2
        bash giwifi-gear-sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -q ipad
        
