name: CI
on:
  push:
    branches:    
      - sh

  watch:
    types: started
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            ref: sh

      - name: ci for sh ver
        env:
          GW_GTW: ${{ secrets.GW_GTW }}
          GW_USERNAME: ${{ secrets.GW_USERNAME }}
          GW_PASSWORD: ${{ secrets.GW_PASSWORD }}
        run: |
          chmod +x ./giwifi-gear.sh
          ./giwifi-gear.sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -q -l
          sleep 10
          ./giwifi-gear.sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -t pc -l
          sleep 10
          ./giwifi-gear.sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -q -l
          sleep 10
          ./giwifi-gear.sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -t mac -l
          sleep 10
          ./giwifi-gear.sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -q -l
          sleep 10
          ./giwifi-gear.sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -t ipad -l
          sleep 10
          ./giwifi-gear.sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -q -l
          sleep 10
          ./giwifi-gear.sh -g ${GW_GTW} -u ${GW_USERNAME} -p ${GW_PASSWORD} -t android -l
